### ISSUE TITLE
Good job

### ISSUE THREAD

**Issue by mustafakameldev** [majidELMEHAMMEDY/world-map-svg#1]
would you add some features : make it for country, add a control way to add pins over country

**Comment by majidELMEHAMMEDY** [comment]
Hey thank you for the remarks but when i published that component i needed
that functionality in one of my projects and i didn't find any component
that serve that purpose so i created it and shared it because maybe someone
else in world would need the same thing and he doesn't have to go through
the same trouble heh so basically i didn't touch it since then but if u are
interested we can collaborate to come up with something better

Best Regards
